name: tugasakhirprak1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^5.5.0
  easy_localization: ^3.0.7
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.2
  http: ^1.2.2
  intl: ^0.19.0
  provider: ^6.1.2
  timeago: ^3.7.0
  translator: ^1.0.3+1
  url_launcher: ^6.1.10
  webview_flutter: ^4.10.0


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
